package nomadrealms.context.game.world.map.area;

import static nomadrealms.context.game.world.map.area.Tile.TILE_HORIZONTAL_SPACING;
import static nomadrealms.context.game.world.map.area.Tile.TILE_VERTICAL_SPACING;
import static nomadrealms.context.game.world.map.area.coordinate.ChunkCoordinate.CHUNK_SIZE;

import engine.common.math.Vector2f;
import nomadrealms.context.game.world.map.area.coordinate.ChunkCoordinate;
import nomadrealms.context.game.world.map.area.coordinate.TileCoordinate;
import nomadrealms.context.game.world.map.generation.MapGenerationStrategy;
import nomadrealms.render.RenderingEnvironment;

/**
 * A chunk is a 16x16 grid of tiles. This is the optimal size for batch rendering. Chunks are how we limit the rendering
 * of tiles to only those that are visible on the screen.
 * <br><br>
 * Chunks should only be generated by a {@link MapGenerationStrategy}.
 * <br><br>
 * Some math:
 * <br>
 * Chunk Dimensions = ({@link Tile#TILE_HORIZONTAL_SPACING TILE_X}, {@link Tile#TILE_VERTICAL_SPACING TILE_Y}) *
 * {@link ChunkCoordinate#CHUNK_SIZE CHUNK SIZE} = (30, 34.64) * 16 = (480, 554.24)
 */
public class Chunk {

	private final transient Zone zone;
	private final ChunkCoordinate coord;

	private Tile[][] tiles;

	/**
	 * No-arg constructor for serialization.
	 */
	protected Chunk() {
		this(null, null);
	}

	public Chunk(Zone zone, ChunkCoordinate coord) {
		this.zone = zone;
		this.coord = coord;
	}

	public Tile tile(int x, int y) {
		return tiles[x][y];
	}

	public void render(RenderingEnvironment re) {
		for (int row = 0; row < CHUNK_SIZE; row++) {
			for (int col = 0; col < CHUNK_SIZE; col++) {
				tiles[row][col].render(re);
			}
		}
		// TODO: instanced rendering - render all tiles in a chunk together
	}

	private Vector2f indexPosition() {
		return new Vector2f(
				coord.x() * TILE_HORIZONTAL_SPACING,
				coord.y() * TILE_VERTICAL_SPACING)
				.scale(CHUNK_SIZE);
	}

	public Vector2f pos() {
		return zone.pos().add(indexPosition());
	}

	public Tile getTile(TileCoordinate tile) {
		assert tile.chunk().equals(coord);
		return tiles[tile.x()][tile.y()];
	}

	public ChunkCoordinate coord() {
		return coord;
	}

	public Zone zone() {
		return zone;
	}

	public void replace(Tile tile) {
		tiles[tile.coord().x()][tile.coord().y()] = tile;
	}

	public void tiles(Tile[][] tiles) {
		this.tiles = tiles;
	}

}
