package nomadrealms.context.game.world.map.area;

import static engine.common.colour.Colour.toRangedVector;
import static nomadrealms.context.game.world.map.area.Tile.TILE_HORIZONTAL_SPACING;
import static nomadrealms.context.game.world.map.area.Tile.TILE_RADIUS;
import static nomadrealms.context.game.world.map.area.Tile.TILE_VERTICAL_SPACING;
import static nomadrealms.context.game.world.map.area.coordinate.ChunkCoordinate.CHUNK_SIZE;
import static nomadrealms.render.vao.shape.HexagonVao.HEIGHT;
import static nomadrealms.render.vao.shape.HexagonVao.SIDE_LENGTH;

import java.util.ArrayList;
import java.util.List;

import engine.common.math.Matrix4f;
import engine.common.math.Vector2f;
import engine.common.math.Vector3f;
import engine.common.math.Vector4f;
import engine.visuals.constraint.box.ConstraintPair;
import nomadrealms.context.game.world.map.area.coordinate.ChunkCoordinate;
import nomadrealms.context.game.world.map.area.coordinate.TileCoordinate;
import nomadrealms.context.game.world.map.generation.MapGenerationStrategy;
import nomadrealms.render.RenderingEnvironment;
import nomadrealms.render.vao.shape.InstancedHexagonVao;

/**
 * A chunk is a 16x16 grid of tiles. This is the optimal size for batch rendering. Chunks are how we limit the rendering
 * of tiles to only those that are visible on the screen.
 * <br><br>
 * Chunks should only be generated by a {@link MapGenerationStrategy}.
 * <br><br>
 * Some math:
 * <br>
 * Chunk Dimensions = ({@link Tile#TILE_HORIZONTAL_SPACING TILE_X}, {@link Tile#TILE_VERTICAL_SPACING TILE_Y}) *
 * {@link ChunkCoordinate#CHUNK_SIZE CHUNK SIZE} = (30, 34.64) * 16 = (480, 554.24)
 */
public class Chunk {

	private transient Zone zone;
	private ChunkCoordinate coord;

	private Tile[][] tiles;

	/**
	 * No-arg constructor for serialization.
	 */
	protected Chunk() {
		this(null, null);
	}

	public Chunk(Zone zone, ChunkCoordinate coord) {
		this.zone = zone;
		this.coord = coord;
	}

	public Tile tile(int x, int y) {
		return tiles[x][y];
	}

	public void render(RenderingEnvironment re) {
		float[] transforms = new float[CHUNK_SIZE * CHUNK_SIZE * 16];
		float[] colors = new float[CHUNK_SIZE * CHUNK_SIZE * 4];
		int i = 0;
		Vector2f toCenter = new Vector2f(TILE_RADIUS * SIDE_LENGTH, TILE_RADIUS * HEIGHT);
		ConstraintPair chunkPos = zone.pos().add(indexPosition());
		for (int row = 0; row < CHUNK_SIZE; row++) {
			for (int col = 0; col < CHUNK_SIZE; col++) {
				Tile tile = tiles[row][col];

				// Calculation logic copied from Tile.indexPosition()
				Vector2f base = new Vector2f(tile.coord().x() * TILE_HORIZONTAL_SPACING, tile.coord().y() * TILE_VERTICAL_SPACING);
				Vector2f columnOffset = new Vector2f(0, (tile.coord().x() % 2 == 0) ? 0 : TILE_RADIUS * HEIGHT);
				ConstraintPair indexPosition = new ConstraintPair(toCenter.add(base).add(columnOffset));

				ConstraintPair position = chunkPos.add(indexPosition);
				Vector2f screenPosition = position.sub(re.camera.position()).vector();
				Matrix4f transform = new Matrix4f(screenPosition.x(), screenPosition.y(), TILE_RADIUS * 2 * SIDE_LENGTH * 0.98f,
						TILE_RADIUS * 2 * SIDE_LENGTH * 0.98f, re.glContext).rotate(0, new Vector3f(0, 0, 1));
				System.arraycopy(transform.toArray(), 0, transforms, i * 16, 16);
				Vector4f color = toRangedVector(tile.color());
				colors[i * 4] = color.x();
				colors[i * 4 + 1] = color.y();
				colors[i * 4 + 2] = color.z();
				colors[i * 4 + 3] = color.w();
				i++;
			}
		}
		InstancedHexagonVao.colorVBO().data(colors).updateData();
		InstancedHexagonVao.transformVBO().data(transforms).updateData();
		re.instancedShaderProgram.use(re.glContext);
		InstancedHexagonVao.instance().drawInstanced(re.glContext, CHUNK_SIZE * CHUNK_SIZE);

		for (int row = 0; row < CHUNK_SIZE; row++) {
			for (int col = 0; col < CHUNK_SIZE; col++) {
				Tile tile = tiles[row][col];
				// Calculation logic copied from Tile.indexPosition()
				Vector2f base = new Vector2f(tile.coord().x() * TILE_HORIZONTAL_SPACING, tile.coord().y() * TILE_VERTICAL_SPACING);
				Vector2f columnOffset = new Vector2f(0, (tile.coord().x() % 2 == 0) ? 0 : TILE_RADIUS * HEIGHT);
				ConstraintPair indexPosition = new ConstraintPair(toCenter.add(base).add(columnOffset));

				ConstraintPair position = chunkPos.add(indexPosition);
				Vector2f screenPosition = position.sub(re.camera.position()).vector();
				tile.renderContent(re, screenPosition);
			}
		}
	}

	private ConstraintPair indexPosition() {
		return new ConstraintPair(new Vector2f(
				coord.x() * TILE_HORIZONTAL_SPACING,
				coord.y() * TILE_VERTICAL_SPACING)
				.scale(CHUNK_SIZE));
	}

	public ConstraintPair pos() {
		return zone.pos().add(indexPosition());
	}

	public Tile getTile(TileCoordinate tile) {
		assert tile.chunk().equals(coord);
		return tiles[tile.x()][tile.y()];
	}

	public ChunkCoordinate coord() {
		return coord;
	}

	public Zone zone() {
		return zone;
	}

	public void replace(Tile tile) {
		tiles[tile.coord().x()][tile.coord().y()] = tile;
	}

	public List<Tile> tiles() {
		List<Tile> tiles = new ArrayList<>();
		for (int x = 0; x < CHUNK_SIZE; x++) {
			for (int y = 0; y < CHUNK_SIZE; y++) {
				tiles.add(this.tiles[x][y]);
			}
		}
		return tiles;
	}

	public void tiles(Tile[][] tiles) {
		this.tiles = tiles;
	}

	public void reinitializeAfterLoad(Zone zone) {
		this.zone = zone;
		for (Tile[] tileRow : tiles) {
			for (Tile tile : tileRow) {
				if (tile != null) {
					tile.reinitializeAfterLoad(this);
				}
			}
		}
	}

}
